print("ingrese 5 numeros enteros")
num1= int(input(print("Ingrese el primer numero: ")))
num2= int(input(print("Ingrese el segundo numero: ")))
num3= int(input(print("Ingrese el tercer numero: ")))
num4= int(input(print("Ingrese el cuarto numero: ")))
num5= Int(input(print("Ingrese el quinto numero: ")))
print()
print("Usted encontrara el resultado de 5 funciones sobre esto numeros que ingreso")
list(num1,num2, num3, num4,num5)
